print("+ Add")
print("- Subtract")
print("* Multiply")
print("/ divide ")
print("% remainder  ")
print("// floor division ")
a= eval (input("Enter the number :-"))
opr= input("Enter the operator:-")
b= eval (input("Enter the number :-"))
if(opr=='+'):print(a+b)
elif(opr=='-'):print(a-b)
elif(opr=='*'):print(a*b)
elif(opr=='/'):print(a/b)
elif(opr=='%'):print(a%b)
elif(opr=='//'):print(a//b)
else:print("Invalid")