t=(1,2,3,4,5)
l=(1)
print(type(l))
print(type(t))
print(t[3])
x=len(t)
print()
for a in range(x):
    print(t[a])
print()
for a in t:
    print(a)
print()
print(t)
print(max(t))
print(min(t))
print(t.count(5))
print(t.count(8))
print(t.index(5))
print(sum(t))
print(sum(t,1))