a=input("Enter the value :-")
b=input("Enter the value :-")
print (a+b)
print (int(a)+int(b))
c=int(input("Enter the value :-"))
d=int(input("Enter the value :-"))
print(c+d)
f=float(input("Enter the value :-"))
e=float(input("Enter the value :-"))
print(e+f)
g=eval(input("Enter the value :-"))
h=eval(input("Enter the value :-"))
print(g+h)